// AdoptionRepository — thin Drizzle wrapper for adoption domain writes and reads.
// Accepts an optional `tx` parameter for use inside db.transaction() calls,
// mirroring the existing openCase(input, tx) pattern in the codebase.
// Returns domain types or lightweight shapes (not raw Drizzle row types).
// No auth logic — auth lives at the action / use-case edge.

import { and, eq, inArray, isNull, ne, sql } from "drizzle-orm";

import {
  attachments,
  cases,
  db,
  organizations,
  ownerships,
  petEvents,
  pets,
  profiles,
  reminders,
} from "@/db";
import { closeCase, findOpenCaseForPetAndKind } from "@/lib/case-helpers";
import { dniLast4, hashDni } from "@/lib/dni-hash";
import { insertEventIdempotent } from "@/lib/event-idempotency";
import { validateEventPayload } from "@/lib/event-schemas";

// ---------------------------------------------------------------------------
// Type aliases
// ---------------------------------------------------------------------------

type Tx = Parameters<Parameters<typeof db.transaction>[0]>[0];
type PetRow = typeof pets.$inferSelect;
type FosterRow = { id: string; ownerUserId: string | null };
type SetEligibilityArgs = {
  petId: string;
  eligible: boolean;
  ineligibleReason: string | null;
  ineligibleReasonNotes: string | null;
  ineligibleUntil: Date | null;
  now: Date;
  userId: string;
  orgId: string;
  orgVerified: boolean;
  /** Previous eligibility state captured by the use-case BEFORE writing. */
  previousState: { eligible: boolean | null; reason: string | null } | null;
};

type SetListingStatusArgs = {
  petId: string;
  action: "publish" | "pause" | "unpause" | "unpublish";
  currentListedAt: Date | null;
  now: Date;
};

type SetBulkEligibilityIdempotentArgs = {
  petId: string;
  eligible: boolean;
  ineligibleReason: string | null;
  ineligibleReasonNotes: string | null;
  ineligibleUntil: Date | null;
  now: Date;
  userId: string;
  orgId: string;
  orgVerified: boolean;
  /** Deterministic UUID derived from (bulkActionId + ":" + petId). */
  clientIdempotencyKey: string;
};

type BatchShelterPetForEligibility = {
  petId: string;
  publicToken: string;
};

type BatchShelterPetForListing = {
  petId: string;
  publicToken: string;
  adoptionListedAt: Date | null;
  status: string;
  adoptionEligible: boolean | null;
  inCustodyDispute: boolean | null;
  rabiesObservationStatus: string | null;
};

type UpdateListingContentArgs = {
  petId: string;
  story?: string | null;
  requirements?: string | null;
  ageBucket?: string | null;
  sizeEstimate?: string | null;
  energyLevel?: string | null;
  goodWithKids?: boolean | null;
  goodWithDogs?: boolean | null;
  goodWithCats?: boolean | null;
  needsYard?: boolean | null;
  feeArs?: number | null;
};

type InsertApplicationArgs = {
  petId: string;
  userId: string;
  orgId: string;
  housingType: string;
  otherPets: string | null;
  dailyRoutine: string | null;
  notes: string | null;
  motivation: string | null;
  priorPets: string | null;
  now: Date;
};

type ResolveApplicationArgs = {
  petId: string;
  applicationEventId: string;
  outcome: "approved" | "rejected" | "withdrawn";
  // For approved/rejected this is the shelter reviewer; for withdrawn it is the
  // applicant's own user id (they are the actor who resolved their application).
  reviewerUserId: string;
  orgId: string;
  orgVerified: boolean;
  reason?: string;
  autoGenerated?: boolean;
  notes: string | null;
  now: Date;
};

type InsertAdoptionFinalizedArgs = {
  petId: string;
  userId: string;
  orgId: string;
  orgVerified: boolean;
  custodyOwnershipId: string;
  adopterUserId: string;
  isStubAdopter: boolean;
  fosterRow: { id: string; ownerUserId: string | null } | null;
  fosterUserId: string | null;
  /** Pre-found custody case id, or null if not intaked. */
  custodyCaseId: string | null;
  displayName: string;
  phone: string | null;
  dni: string | null;
  contractAttachmentId: string | null;
  /** Supabase Storage path of the uploaded contract file (null when no file). */
  contractStoragePath: string | null;
  /** MIME type of the uploaded contract file (null when no file). */
  contractMimeType: string | null;
  /** Byte size of the stored (possibly re-encoded) contract file (null when no file). */
  contractFileSize: number | null;
  followupMonths: number | null;
  notes: string | null;
  /** Organization display name — used in reminder description copy. */
  orgDisplayName: string;
  /** Pet name — used in reminder description copy. */
  petName: string;
  now: Date;
};

type ShelterPetResult = (PetRow & { custodyOwnershipId: string }) | null;

type OrgRow = typeof organizations.$inferSelect;

type PetWithOrgResult = {
  pet: PetRow & { custodyOwnershipId: string };
  org: OrgRow;
} | null;

// NOTE: ApplicationEventRow is intentionally NOT exported from the repository
// public surface. Callers receive only the projected shape defined per method.
// Keeping the raw row type internal prevents accidental PII leaks (the payload
// carries applicant name/phone/address/DNI) across module boundaries.
type ApplicationEventRow = typeof petEvents.$inferSelect;

/**
 * Projected application shape returned by findApplicationForReview.
 * Contains only the fields the review/info-request callers need.
 * The full event (including PII payload) stays in the immutable event log.
 */
type ApplicationReviewShape = {
  id: string;
  /** Extracted from payload — the only PII field callers legitimately need. */
  applicantUserId: string | null;
};

// ---------------------------------------------------------------------------
// Repository
// ---------------------------------------------------------------------------

export const AdoptionRepository = {
  /**
   * Finds a pet by public token that is currently under active shelter_custody
   * by the given organization. Returns the pet row + custodyOwnershipId, or null.
   */
  async findShelterPet(
    petPublicToken: string,
    organizationId: string,
    tx?: Tx,
  ): Promise<ShelterPetResult> {
    const client = tx ?? db;
    const [row] = await client
      .select({ pet: pets, custodyOwnershipId: ownerships.id })
      .from(pets)
      .innerJoin(ownerships, eq(ownerships.petId, pets.id))
      .where(
        and(
          eq(pets.publicToken, petPublicToken),
          eq(ownerships.ownerOrganizationId, organizationId),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
        ),
      )
      .limit(1);

    if (!row) return null;
    return { ...row.pet, custodyOwnershipId: row.custodyOwnershipId };
  },

  /**
   * Finds the active foster ownership row for a pet, or null if none.
   */
  async findActiveFoster(petId: string, tx?: Tx): Promise<FosterRow | null> {
    const client = tx ?? db;
    const [row] = await client
      .select({ id: ownerships.id, ownerUserId: ownerships.ownerUserId })
      .from(ownerships)
      .where(
        and(eq(ownerships.petId, petId), eq(ownerships.role, "foster"), isNull(ownerships.endedAt)),
      )
      .limit(1);

    return row ?? null;
  },

  /**
   * Finds a profile by DNI (via hash — no plaintext comparison).
   * Wave 5 Item 25a: equality matching uses HMAC-SHA256 hash, never plaintext.
   */
  async findStubAdopterByDni(dni: string, tx?: Tx): Promise<{ id: string } | null> {
    const client = tx ?? db;
    const [row] = await client
      .select({ id: profiles.id })
      .from(profiles)
      .where(eq(profiles.dniHash, hashDni(dni)))
      .limit(1);
    return row ?? null;
  },

  /**
   * Updates adoption eligibility and inserts the adoption_eligibility_set event.
   * Must be called inside a db.transaction().
   */
  async setEligibility(args: SetEligibilityArgs, tx: Tx): Promise<void> {
    await tx
      .update(pets)
      .set({
        adoptionEligible: args.eligible,
        adoptionIneligibleReason: args.eligible ? null : (args.ineligibleReason ?? null),
        adoptionIneligibleReasonNotes: args.eligible ? null : (args.ineligibleReasonNotes ?? null),
        adoptionIneligibleUntil: args.eligible ? null : args.ineligibleUntil,
        adoptionEligibilitySetAt: args.now,
        adoptionEligibilitySetByUserId: args.userId,
        updatedAt: args.now,
      })
      .where(eq(pets.id, args.petId));

    const payload = validateEventPayload("adoption_eligibility_set", {
      eligible: args.eligible,
      ineligible_reason: args.eligible ? null : (args.ineligibleReason ?? null),
      ineligible_reason_notes: args.eligible ? null : (args.ineligibleReasonNotes ?? null),
      ineligible_until: args.eligible
        ? null
        : args.ineligibleUntil
          ? args.ineligibleUntil.toISOString()
          : null,
      // Previous state captured by the use-case before calling setEligibility.
      previous_state: args.previousState ?? null,
    });

    await tx.insert(petEvents).values({
      petId: args.petId,
      eventType: "adoption_eligibility_set",
      occurredAt: args.now,
      recordedAt: args.now,
      recordedByUserId: args.userId,
      authorRole: "shelter",
      authorOrganizationId: args.orgId,
      authorVerified: args.orgVerified,
      payload,
    });
  },

  /**
   * Updates the listing status fields. No event emitted — listing is
   * shelf-curated metadata, not a pet-fact event.
   */
  async setListingStatus(args: SetListingStatusArgs, tx?: Tx): Promise<void> {
    const client = tx ?? db;

    if (args.action === "publish") {
      await client
        .update(pets)
        .set({
          adoptionListedAt: args.currentListedAt ?? args.now,
          adoptionListingPausedAt: null,
          updatedAt: args.now,
        })
        .where(eq(pets.id, args.petId));
    } else if (args.action === "unpublish") {
      await client
        .update(pets)
        .set({ adoptionListedAt: null, adoptionListingPausedAt: null, updatedAt: args.now })
        .where(eq(pets.id, args.petId));
    } else if (args.action === "pause") {
      await client
        .update(pets)
        .set({ adoptionListingPausedAt: args.now, updatedAt: args.now })
        .where(eq(pets.id, args.petId));
    } else {
      // unpause
      await client
        .update(pets)
        .set({ adoptionListingPausedAt: null, updatedAt: args.now })
        .where(eq(pets.id, args.petId));
    }
  },

  // ---------------------------------------------------------------------------
  // Bulk operations
  // ---------------------------------------------------------------------------

  /**
   * Batch ownership query for bulk eligibility writes.
   *
   * Returns only pets under active shelter_custody of the given org that are
   * NOT deceased — matches the single-pet requireAlivePetAccess scope.
   */
  async findBatchShelterPetsForEligibility(
    tokens: string[],
    orgId: string,
  ): Promise<BatchShelterPetForEligibility[]> {
    if (tokens.length === 0) return [];
    return db
      .select({ petId: pets.id, publicToken: pets.publicToken })
      .from(pets)
      .innerJoin(ownerships, eq(ownerships.petId, pets.id))
      .where(
        and(
          inArray(pets.publicToken, tokens),
          eq(ownerships.ownerOrganizationId, orgId),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
          ne(pets.status, "deceased"),
        ),
      );
  },

  /**
   * Batch ownership query for bulk listing publish/unpublish.
   *
   * Fetches the extra columns needed to evaluate publish guards (D18–D21)
   * per pet in the loop. Same scope as findBatchShelterPetsForEligibility.
   */
  async findBatchShelterPetsForListing(
    tokens: string[],
    orgId: string,
  ): Promise<BatchShelterPetForListing[]> {
    if (tokens.length === 0) return [];
    return db
      .select({
        petId: pets.id,
        publicToken: pets.publicToken,
        adoptionListedAt: pets.adoptionListedAt,
        status: pets.status,
        adoptionEligible: pets.adoptionEligible,
        inCustodyDispute: pets.inCustodyDispute,
        rabiesObservationStatus: pets.rabiesObservationStatus,
      })
      .from(pets)
      .innerJoin(ownerships, eq(ownerships.petId, pets.id))
      .where(
        and(
          inArray(pets.publicToken, tokens),
          eq(ownerships.ownerOrganizationId, orgId),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
          ne(pets.status, "deceased"),
        ),
      );
  },

  /**
   * Atomically updates pet eligibility columns and inserts an
   * adoption_eligibility_set event using insertEventIdempotent.
   *
   * Differs from setEligibility: uses idempotency-key deduplication so
   * re-submitting the same bulkActionId is a safe no-op (wasNoop=true).
   * The previous_state is null for the bulk path (performance: no pre-load).
   *
   * Must be called inside a db.transaction().
   */
  async setBulkEligibilityIdempotent(
    args: SetBulkEligibilityIdempotentArgs,
    tx: Tx,
  ): Promise<{ wasNoop: boolean }> {
    // UPDATE pets eligibility columns (last-write-wins — idempotent on retry).
    await tx
      .update(pets)
      .set({
        adoptionEligible: args.eligible,
        adoptionIneligibleReason: args.eligible ? null : (args.ineligibleReason ?? null),
        adoptionIneligibleReasonNotes: args.eligible ? null : (args.ineligibleReasonNotes ?? null),
        adoptionIneligibleUntil: args.eligible ? null : args.ineligibleUntil,
        adoptionEligibilitySetAt: args.now,
        adoptionEligibilitySetByUserId: args.userId,
        updatedAt: args.now,
      })
      .where(eq(pets.id, args.petId));

    const payload = validateEventPayload("adoption_eligibility_set", {
      eligible: args.eligible,
      ineligible_reason: args.eligible ? null : (args.ineligibleReason ?? null),
      ineligible_reason_notes: args.eligible ? null : (args.ineligibleReasonNotes ?? null),
      ineligible_until: args.eligible
        ? null
        : args.ineligibleUntil
          ? args.ineligibleUntil.toISOString()
          : null,
      // Bulk path: previous_state is null for performance (no per-pet pre-load).
      previous_state: null,
    });

    const { wasNoop } = await insertEventIdempotent(
      {
        petId: args.petId,
        eventType: "adoption_eligibility_set",
        occurredAt: args.now,
        recordedAt: args.now,
        recordedByUserId: args.userId,
        authorRole: "shelter",
        authorOrganizationId: args.orgId,
        authorVerified: args.orgVerified,
        payload,
        notes: null,
        clientIdempotencyKey: args.clientIdempotencyKey,
      },
      tx as Parameters<typeof insertEventIdempotent>[1],
    );

    return { wasNoop };
  },

  /**
   * Updates the listing content fields. No event emitted.
   */
  async updateListingContent(args: UpdateListingContentArgs, tx?: Tx): Promise<void> {
    const client = tx ?? db;
    await client
      .update(pets)
      .set({
        adoptionStory: args.story?.trim() || null,
        adoptionRequirements: args.requirements?.trim() || null,
        adoptionAgeBucket: (args.ageBucket ??
          null) as (typeof pets.$inferSelect)["adoptionAgeBucket"],
        adoptionSizeEstimate: (args.sizeEstimate ??
          null) as (typeof pets.$inferSelect)["adoptionSizeEstimate"],
        adoptionEnergyLevel: (args.energyLevel ??
          null) as (typeof pets.$inferSelect)["adoptionEnergyLevel"],
        adoptionGoodWithKids: args.goodWithKids ?? null,
        adoptionGoodWithDogs: args.goodWithDogs ?? null,
        adoptionGoodWithCats: args.goodWithCats ?? null,
        adoptionNeedsYard: args.needsYard ?? null,
        adoptionFeeArs: args.feeArs ?? null,
        updatedAt: new Date(),
      })
      .where(eq(pets.id, args.petId));
  },

  /**
   * Inserts an adoption_application_submitted event. Must be called inside
   * a db.transaction() so the org member fan-out can share the same tx.
   */
  async insertApplication(args: InsertApplicationArgs, tx: Tx): Promise<{ eventId: string }> {
    const payload = validateEventPayload("adoption_application_submitted", {
      applicant_user_id: args.userId,
      related_organization_id: args.orgId,
      housing_type: args.housingType,
      other_pets: args.otherPets,
      daily_routine: args.dailyRoutine,
      notes: args.notes,
      profile_sharing_consent_at: args.now.toISOString(),
      motivation: args.motivation ?? undefined,
      prior_pets: args.priorPets ?? undefined,
    });

    const [eventRow] = await tx
      .insert(petEvents)
      .values({
        petId: args.petId,
        eventType: "adoption_application_submitted",
        occurredAt: args.now,
        recordedAt: args.now,
        recordedByUserId: args.userId,
        authorRole: "owner",
        authorOrganizationId: null,
        authorVerified: false,
        payload,
      })
      .returning({ id: petEvents.id });

    return { eventId: eventRow.id };
  },

  /**
   * Finds a pet + its shelter org for the application submit flow.
   * Does NOT require the pet to belong to a specific org (applicant is a public user).
   */
  async findPetForApplication(petPublicToken: string, tx?: Tx): Promise<PetWithOrgResult> {
    const client = tx ?? db;
    const [row] = await client
      .select({ pet: pets, custodyOwnershipId: ownerships.id, org: organizations })
      .from(pets)
      .innerJoin(ownerships, eq(ownerships.petId, pets.id))
      .innerJoin(organizations, eq(organizations.id, ownerships.ownerOrganizationId))
      .where(
        and(
          eq(pets.publicToken, petPublicToken),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
        ),
      )
      .limit(1);

    if (!row) return null;
    return { pet: { ...row.pet, custodyOwnershipId: row.custodyOwnershipId }, org: row.org };
  },

  /**
   * Finds the applicant's profile (accountType check).
   */
  async findApplicantProfile(
    userId: string,
    tx?: Tx,
  ): Promise<typeof profiles.$inferSelect | null> {
    const client = tx ?? db;
    const [row] = await client.select().from(profiles).where(eq(profiles.id, userId)).limit(1);
    return row ?? null;
  },

  /**
   * Finds an existing unresolved adoption application for the (petId, userId) pair.
   * Returns the event row or null.
   */
  async findExistingApplication(
    petId: string,
    userId: string,
    tx?: Tx,
  ): Promise<{ id: string } | null> {
    const client = tx ?? db;
    const rows = await client.execute<{ id: string }>(sql`
      SELECT e.id::text AS id
      FROM pet_events e
      WHERE e.pet_id = ${petId}
        AND e.event_type = 'adoption_application_submitted'
        AND e.payload->>'applicant_user_id' = ${userId}
        AND NOT EXISTS (
          SELECT 1 FROM pet_events d
          WHERE d.pet_id = e.pet_id
            AND d.event_type = 'adoption_application_resolved'
            AND d.payload->>'application_event_id' = e.id::text
        )
      LIMIT 1
    `);
    return rows[0] ?? null;
  },

  /**
   * Finds admin/coordinator members of an org to fan-out notifications to.
   */
  async findOrgMembersForNotify(orgId: string, tx?: Tx): Promise<{ userId: string }[]> {
    const client = tx ?? db;
    const rows = await client.execute<{ user_id: string }>(sql`
      SELECT user_id
      FROM organization_memberships
      WHERE organization_id = ${orgId}
        AND left_at IS NULL
        AND role IN ('admin', 'coordinator')
      LIMIT 25
    `);
    return rows.map((r) => ({ userId: r.user_id }));
  },

  /**
   * Loads a pending application for org-side review (approve/reject/info-request).
   * Verifies the pet is under active shelter_custody of the given org.
   *
   * PII fix (Item 27): projects ONLY the fields callers need. The full event
   * payload (which may contain applicant name/phone/address/DNI from the
   * adoption_application_submitted event) is kept in the immutable event log
   * but is never returned to callers. applicantUserId is the single PII field
   * the review and notification flows legitimately require.
   */
  async findApplicationForReview(
    applicationEventId: string,
    organizationId: string,
    tx?: Tx,
  ): Promise<
    | {
        application: ApplicationReviewShape;
        pet: { id: string; name: string; publicToken: string };
      }
    | { error: string }
  > {
    const client = tx ?? db;
    const [row] = await client
      .select({
        applicationId: petEvents.id,
        // Extract only applicant_user_id from the payload — the single field
        // callers need for notification routing. Name/phone/address/DNI stay
        // in the immutable event log and are never returned.
        applicantUserId: sql<string | null>`${petEvents.payload}->>'applicant_user_id'`,
        petId: pets.id,
        petName: pets.name,
        petPublicToken: pets.publicToken,
      })
      .from(petEvents)
      .innerJoin(pets, eq(pets.id, petEvents.petId))
      .innerJoin(ownerships, eq(ownerships.petId, pets.id))
      .where(
        and(
          eq(petEvents.id, applicationEventId),
          eq(petEvents.eventType, "adoption_application_submitted"),
          eq(ownerships.ownerOrganizationId, organizationId),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
        ),
      )
      .limit(1);

    if (!row) {
      return { error: "Postulación no encontrada o no pertenece a tu organización." };
    }

    // Check: already resolved?
    const decided = await client.execute<{ id: string }>(sql`
      SELECT id FROM pet_events
      WHERE pet_id = ${row.petId}
        AND event_type = 'adoption_application_resolved'
        AND payload->>'application_event_id' = ${applicationEventId}
      LIMIT 1
    `);
    if (decided.length > 0) {
      return { error: "Esta postulación ya fue resuelta." };
    }

    // Check: pet already finalized?
    const finalized = await client.execute<{ id: string }>(sql`
      SELECT id FROM pet_events
      WHERE pet_id = ${row.petId}
        AND event_type = 'adoption_finalized'
      LIMIT 1
    `);
    if (finalized.length > 0) {
      return { error: "Esta mascota ya fue adoptada — no es posible revisar postulaciones." };
    }

    return {
      application: { id: row.applicationId, applicantUserId: row.applicantUserId },
      pet: { id: row.petId, name: row.petName, publicToken: row.petPublicToken },
    };
  },

  /**
   * Finds all pending applications for a pet (for auto-rejection cascade).
   * Excludes a specific adopter's application (the one who just adopted).
   */
  async findPendingApplicationsExcluding(
    petId: string,
    excludeUserId: string,
    tx: Tx,
  ): Promise<{ applicationId: string; applicantUserId: string }[]> {
    const rows = await tx.execute<{ application_id: string; applicant_user_id: string }>(sql`
      SELECT e.id::text AS application_id,
             e.payload->>'applicant_user_id' AS applicant_user_id
      FROM pet_events e
      WHERE e.pet_id = ${petId}
        AND e.event_type = 'adoption_application_submitted'
        AND e.payload->>'applicant_user_id' <> ${excludeUserId}
        AND NOT EXISTS (
          SELECT 1 FROM pet_events d
          WHERE d.pet_id = e.pet_id
            AND d.event_type = 'adoption_application_resolved'
            AND d.payload->>'application_event_id' = e.id::text
        )
    `);
    return rows.map((r) => ({
      applicationId: r.application_id,
      applicantUserId: r.applicant_user_id,
    }));
  },

  /**
   * Finds the open custody_episode case for a pet, or null if none.
   * Used by the finalize-adoption use-case to get the case id before the tx.
   */
  async findOpenCustodyCase(petId: string): Promise<{ id: string } | null> {
    return findOpenCaseForPetAndKind(petId, "custody_episode");
  },

  /**
   * Composite atomic write for finalizing an adoption. Must be called inside a
   * db.transaction(). Handles:
   *   - optional stub profile insert
   *   - close shelter_custody ownership
   *   - close foster ownership + foster_placement case (if active foster)
   *   - insert new owner row
   *   - insert adoption_finalized event
   *   - close custody_episode case (if open)
   *   - auto-reject pending applications cascade (done by caller after getting pendingApps)
   *   - optional contract attachment insert
   *   - optional reminder rows insert
   */
  async insertAdoptionFinalized(
    args: InsertAdoptionFinalizedArgs,
    tx: Tx,
  ): Promise<{ eventId: string }> {
    const {
      petId,
      userId,
      orgId,
      orgVerified,
      custodyOwnershipId,
      adopterUserId,
      isStubAdopter,
      fosterRow,
      fosterUserId,
      custodyCaseId,
      displayName,
      phone,
      dni,
      contractAttachmentId,
      contractStoragePath,
      contractMimeType,
      contractFileSize,
      followupMonths,
      notes,
      orgDisplayName,
      petName,
      now,
    } = args;

    // Stub profile insert. No plaintext DNI (Wave 5 Item 25a).
    if (isStubAdopter && dni) {
      await tx.insert(profiles).values({
        id: adopterUserId,
        displayName,
        phone,
        dniHash: hashDni(dni),
        dniLast4: dniLast4(dni),
        dniVerified: false,
        role: "owner",
      });
    }

    // Close shelter_custody.
    await tx.update(ownerships).set({ endedAt: now }).where(eq(ownerships.id, custodyOwnershipId));

    // Close foster (if any).
    if (fosterRow) {
      await tx.update(ownerships).set({ endedAt: now }).where(eq(ownerships.id, fosterRow.id));
      // Close foster_placement case alongside the foster ownership row.
      const [fosterCase] = await tx
        .select({ id: cases.id })
        .from(cases)
        .where(
          and(
            eq(cases.primaryPetId, petId),
            eq(cases.caseKind, "foster_placement"),
            eq(cases.status, "open"),
          ),
        )
        .limit(1);
      if (fosterCase?.id) {
        await closeCase({ caseId: fosterCase.id, reason: "resolved", closedByUserId: userId }, tx);
      }
    }

    // Insert new owner row.
    await tx.insert(ownerships).values({
      petId,
      ownerUserId: adopterUserId,
      role: "owner",
      startedAt: now,
      transferredFromId: custodyOwnershipId,
    });

    // Insert adoption_finalized event.
    const payload = validateEventPayload("adoption_finalized", {
      previous_owner_organization_id: orgId,
      adopter_user_id: adopterUserId,
      foster_user_id: fosterUserId,
      contract_attachment_id: contractAttachmentId,
      post_adoption_followup_months: followupMonths,
      notes,
    });

    const [adoptionEvent] = await tx
      .insert(petEvents)
      .values({
        petId,
        eventType: "adoption_finalized",
        occurredAt: now,
        recordedAt: now,
        recordedByUserId: userId,
        authorRole: "shelter",
        authorOrganizationId: orgId,
        authorVerified: orgVerified,
        payload,
        caseId: custodyCaseId ?? null,
      })
      .returning({ id: petEvents.id });

    // Close custody_episode case.
    if (custodyCaseId) {
      await closeCase({ caseId: custodyCaseId, reason: "resolved", closedByUserId: userId }, tx);
    }

    // Contract attachment row.
    // The storage upload happens pre-tx in the action; the action passes the
    // resulting storagePath, mimeType, and fileSize alongside contractAttachmentId.
    // Caller handles orphan cleanup on error (storage delete + throw).
    if (contractAttachmentId && contractStoragePath && contractMimeType) {
      await tx.insert(attachments).values({
        id: contractAttachmentId,
        petId,
        eventId: adoptionEvent.id,
        uploadedByUserId: userId,
        storagePath: contractStoragePath,
        mimeType: contractMimeType,
        fileSize: contractFileSize ?? null,
      });
    }

    // Reminder rows for non-stub adopter.
    const CHECKIN_WINDOWS = [1, 3, 6, 12] as const;
    if (!isStubAdopter && followupMonths !== null && followupMonths > 0) {
      const dueWindows = CHECKIN_WINDOWS.filter((m) => m <= followupMonths);
      if (dueWindows.length > 0) {
        await tx.insert(reminders).values(
          dueWindows.map((m) => {
            const dueDate = new Date(now);
            dueDate.setMonth(dueDate.getMonth() + m);
            return {
              petId,
              userId: adopterUserId,
              reminderType: "post_adoption_checkin" as const,
              dueAt: dueDate,
              title: `Seguimiento post-adopción a los ${m} ${m === 1 ? "mes" : "meses"}`,
              description: `${orgDisplayName} pidió un check-in sobre ${petName}. Subí fotos y contanos cómo está.`,
              sourceEventId: adoptionEvent.id,
            };
          }),
        );
      }
    }

    return { eventId: adoptionEvent.id };
  },

  /**
   * Inserts an adoption_application_resolved event (approve or reject).
   * Must be called inside a db.transaction().
   */
  async resolveApplication(args: ResolveApplicationArgs, tx: Tx): Promise<void> {
    const payload = validateEventPayload("adoption_application_resolved", {
      application_event_id: args.applicationEventId,
      reviewer_user_id: args.reviewerUserId,
      outcome: args.outcome,
      reason: args.outcome === "rejected" ? (args.reason ?? "manual_rejection") : undefined,
      auto_generated: args.autoGenerated ?? false,
      notes: args.notes ?? null,
    });

    await tx.insert(petEvents).values({
      petId: args.petId,
      eventType: "adoption_application_resolved",
      occurredAt: args.now,
      recordedAt: args.now,
      recordedByUserId: args.reviewerUserId,
      authorRole: "shelter",
      authorOrganizationId: args.orgId,
      authorVerified: args.orgVerified,
      payload,
    });
  },

  /**
   * Loads a pending application for the APPLICANT-side withdrawal flow.
   *
   * Verifies, in one read:
   *   - the event exists and is an adoption_application_submitted
   *   - the caller (applicantUserId) is the submitter (ownership guard)
   *   - the application is still unresolved (no adoption_application_resolved
   *     for it) — same NOT EXISTS pending-derivation the postulaciones list
   *     and the org review query use.
   *
   * Returns the application + pet (id, name) + the shelter org id (for the
   * org-side notification), or an error string.
   */
  async findApplicationForWithdrawal(
    applicationEventId: string,
    applicantUserId: string,
    tx?: Tx,
  ): Promise<
    | {
        application: { id: string };
        pet: { id: string; name: string };
        org: { id: string; publicToken: string; displayName: string };
      }
    | { error: string }
  > {
    const client = tx ?? db;
    const [row] = await client
      .select({
        applicationId: petEvents.id,
        applicantUserId: sql<string>`${petEvents.payload}->>'applicant_user_id'`,
        petId: pets.id,
        petName: pets.name,
        orgId: organizations.id,
        orgPublicToken: organizations.publicToken,
        orgDisplayName: organizations.displayName,
      })
      .from(petEvents)
      .innerJoin(pets, eq(pets.id, petEvents.petId))
      .innerJoin(
        ownerships,
        and(
          eq(ownerships.petId, pets.id),
          eq(ownerships.role, "shelter_custody"),
          isNull(ownerships.endedAt),
        ),
      )
      .innerJoin(organizations, eq(organizations.id, ownerships.ownerOrganizationId))
      .where(
        and(
          eq(petEvents.id, applicationEventId),
          eq(petEvents.eventType, "adoption_application_submitted"),
        ),
      )
      .limit(1);

    if (!row) {
      return { error: "No encontramos esta postulación." };
    }
    if (row.applicantUserId !== applicantUserId) {
      return { error: "Solo podés retirar tus propias postulaciones." };
    }

    // Already resolved (approved / rejected / closed / withdrawn)?
    const decided = await client.execute<{ id: string }>(sql`
      SELECT id FROM pet_events
      WHERE pet_id = ${row.petId}
        AND event_type = 'adoption_application_resolved'
        AND payload->>'application_event_id' = ${applicationEventId}
      LIMIT 1
    `);
    if (decided.length > 0) {
      return { error: "Esta postulación ya fue resuelta y no se puede retirar." };
    }

    // Pet already adopted? A finalize cascade should already have resolved
    // this application, but defend anyway.
    const finalized = await client.execute<{ id: string }>(sql`
      SELECT id FROM pet_events
      WHERE pet_id = ${row.petId} AND event_type = 'adoption_finalized'
      LIMIT 1
    `);
    if (finalized.length > 0) {
      return { error: "Esta postulación ya fue resuelta y no se puede retirar." };
    }

    return {
      application: { id: row.applicationId },
      pet: { id: row.petId, name: row.petName },
      org: {
        id: row.orgId,
        publicToken: row.orgPublicToken,
        displayName: row.orgDisplayName,
      },
    };
  },

  /**
   * Inserts a lightweight `note_added` marker (kind=adoption_info_requested)
   * recording that the shelter probed an adoption application for more info.
   * Reuses note_added (category=system) rather than a new event type — the
   * marker carries the application_event_id so both sides can derive the
   * "info requested" state (applicant: "te pidieron más info"; org: probed row).
   *
   * Attached to the application's pet, authored by the shelter org. Idempotent
   * by intent at the action layer (a re-probe simply appends a newer marker —
   * the derivation reads the latest).
   */
  async insertInfoRequestedNote(
    args: {
      petId: string;
      applicationEventId: string;
      reviewerUserId: string;
      orgId: string;
      orgVerified: boolean;
      message: string;
      now: Date;
    },
    tx?: Tx,
  ): Promise<void> {
    const client = tx ?? db;
    const payload = validateEventPayload("note_added", {
      category: "system",
      text: args.message,
      kind: "adoption_info_requested",
      application_event_id: args.applicationEventId,
    });

    await client.insert(petEvents).values({
      petId: args.petId,
      eventType: "note_added",
      occurredAt: args.now,
      recordedAt: args.now,
      recordedByUserId: args.reviewerUserId,
      authorRole: "shelter",
      authorOrganizationId: args.orgId,
      authorVerified: args.orgVerified,
      payload,
    });
  },

  /**
   * Inserts an adoption_application_resolved event with outcome=withdrawn.
   * The author is the APPLICANT (owner role, no org) — distinct from the
   * shelter-authored approve/reject path. Must be called inside a
   * db.transaction().
   */
  async withdrawApplication(
    args: { petId: string; applicationEventId: string; applicantUserId: string; now: Date },
    tx: Tx,
  ): Promise<void> {
    const payload = validateEventPayload("adoption_application_resolved", {
      application_event_id: args.applicationEventId,
      reviewer_user_id: args.applicantUserId,
      outcome: "withdrawn",
      auto_generated: false,
      notes: null,
    });

    await tx.insert(petEvents).values({
      petId: args.petId,
      eventType: "adoption_application_resolved",
      occurredAt: args.now,
      recordedAt: args.now,
      recordedByUserId: args.applicantUserId,
      authorRole: "owner",
      authorOrganizationId: null,
      authorVerified: false,
      payload,
    });
  },
};
