// maplibre worker wiring fence.
//
// WHAT WENT WRONG, so the fence's shape makes sense. maplibre-gl 6 asks for its
// worker at runtime via `new URL('./maplibre-gl-worker.mjs', import.meta.url)`.
// No bundler resolves that statically, so webpack emits no asset — measured on
// this tree: after a clean `pnpm build`, `find .next -iname "*worker*"` returns
// nothing. The fetch then does NOT 404; Next serves the app's own HTML with a
// 200, the worker executes HTML as JavaScript and dies without a word. The map
// registers every layer and source and renders ZERO features, with an empty
// console. It cost a full day of ruling out the database, WebGL2, the load
// handler, legacy expressions and the CSP — every one of them a correct answer
// to the wrong question.
//
// WHY THIS FENCE DOES NOT CHECK FILE BYTES as its main job. `public/maplibre/`
// is generated by `prebuild`/`predev` and gitignored, so version drift between
// the copy and the installed package cannot survive a build. What CAN rot is
// the WIRING — and the way it rots is silent, which is the whole problem:
//
//   · a fifth `import("maplibre-gl")` added somewhere, bypassing the loader and
//     therefore `setWorkerUrl`. That component's map goes quiet, nothing else.
//   · `prebuild` dropped from package.json in a cleanup. The files stop being
//     generated and every map goes quiet at once.
//   · the URL constant and the copy destination drifting apart.
//   · a future maplibre reaching for a different file than the two copied.
//
// None of those produce an error anywhere. All four are checked below.
import { existsSync, globSync, readFileSync } from "node:fs";
import { join } from "node:path";

import {
  MAPLIBRE_PUBLIC_DIR,
  MAPLIBRE_WORKER_ASSETS,
  SHARED_SPECIFIER,
  maplibreDistDir,
  maplibreVersion,
  sha,
} from "./copy-maplibre-worker";

const problems: string[] = [];

const LOADER = "lib/ui/maplibre-loader.ts";
const COPY_SCRIPT = "scripts/copy-maplibre-worker.ts";

const VALUE_IMPORT = /\bimport\s*\(\s*["']maplibre-gl["']\s*\)/;

/** End index of the string literal that starts at `start`. */
function endOfString(source: string, start: number): number {
  const quote = source[start];
  let i = start + 1;
  while (i < source.length) {
    if (source[i] === "\\") {
      i += 2;
      continue;
    }
    if (source[i] === quote) return i + 1;
    i++;
  }
  return source.length;
}

/** Index just past the `*\/` that closes the block comment opening at `start`. */
function endOfBlockComment(source: string, start: number): number {
  const close = source.indexOf("*/", start + 2);
  return close === -1 ? source.length : close + 2;
}

/**
 * Source with its comments removed.
 *
 * WITHOUT THIS THE FENCE PUNISHES THE DOCUMENTATION, which is a mistake this
 * repo has made before and wrote down: a scan over raw source flags the comment
 * that explains why a symbol is NOT used. On its first run this fence named
 * five offenders and two of them were prose — `CabaInset.test.tsx` and
 * `StaticFirstMap.tsx` each describe the dynamic-import idiom in a header
 * comment. Telling somebody to fix a sentence is how a fence teaches people to
 * delete their comments.
 *
 * String-aware, so a `https://` inside a literal does not eat the rest of the
 * line — that would be a FALSE NEGATIVE, the direction a fence may never fail
 * in.
 */
export function stripComments(source: string): string {
  const out: string[] = [];
  let i = 0;
  while (i < source.length) {
    const ch = source[i];
    const next = source[i + 1];
    if (ch === "/" && next === "*") {
      i = endOfBlockComment(source, i);
    } else if (ch === "/" && next === "/") {
      while (i < source.length && source[i] !== "\n") i++;
      out.push("\n");
    } else if (ch === '"' || ch === "'" || ch === "`") {
      const end = endOfString(source, i);
      out.push(source.slice(i, end));
      i = end;
    } else {
      out.push(ch ?? "");
      i++;
    }
  }
  return out.join("");
}

// --- 1. every runtime load goes through the one door ----------------------
//
// `import type` is erased at compile time and cannot reach setWorkerUrl's
// ordering problem, so only VALUE imports count. The loader is the one
// legitimate site.
const sources = globSync("{app,components,lib,src}/**/*.{ts,tsx}", {
  exclude: (p) => p.includes("node_modules"),
});
const offenders = sources
  .map((f) => f.replaceAll("\\", "/"))
  .filter((f) => f !== LOADER)
  .filter((f) => VALUE_IMPORT.test(stripComments(readFileSync(f, "utf8"))));

if (offenders.length > 0) {
  problems.push(
    [
      `${offenders.length} file(s) import maplibre-gl at runtime without going through ${LOADER}:`,
      ...offenders.map((f) => `    ${f}`),
      "  `setWorkerUrl` must run before the first `new Map()`, and that ordering is only",
      "  enforceable from one door. A map built from a bypassing import registers its layers,",
      "  fetches nothing, and draws an empty canvas with no console output.",
      "  Use `loadMapLibre()`. `import type` is fine and is not what this matched.",
    ].join("\n"),
  );
}

// Non-vacuity: if the scan cannot see the loader's own import, the regex died
// and every reassuring line above judged nothing.
const loaderText = readFileSync(LOADER, "utf8");
if (!VALUE_IMPORT.test(stripComments(loaderText))) {
  problems.push(
    `the scan found no runtime import even in ${LOADER} itself — the detection regex is dead, so the check above judged nothing.`,
  );
}

// --- 2. the build still regenerates the files -----------------------------
const pkg = JSON.parse(readFileSync("package.json", "utf8")) as {
  scripts?: Record<string, string>;
};
for (const hook of ["prebuild", "predev"]) {
  if (!pkg.scripts?.[hook]?.includes("copy-maplibre-worker")) {
    problems.push(
      `package.json has no \`${hook}\` running ${COPY_SCRIPT}. \`${MAPLIBRE_PUBLIC_DIR}\` is gitignored on purpose, so without this hook the worker is simply absent in every fresh checkout and every map is blank.`,
    );
  }
}

// --- 3. the served URL and the copy destination agree ---------------------
const servedRoot = MAPLIBRE_PUBLIC_DIR.replaceAll("\\", "/").replace(/^public\//, "");
const expectedUrl = `/${servedRoot}/${MAPLIBRE_WORKER_ASSETS[0]}`;
const declared = loaderText.match(/MAPLIBRE_WORKER_URL\s*=\s*["']([^"']+)["']/)?.[1];
if (declared !== expectedUrl) {
  problems.push(
    `${LOADER} serves the worker from "${declared}" but ${COPY_SCRIPT} copies it to "${expectedUrl}". One of the two moved, and what the browser gets is a 200 carrying the app's HTML.`,
  );
}

// --- 4. the installed worker still needs exactly what we copy -------------
const dist = maplibreDistDir();
const version = maplibreVersion();
const workerSource = readFileSync(join(dist, MAPLIBRE_WORKER_ASSETS[0]), "utf8");
if (!workerSource.includes(SHARED_SPECIFIER)) {
  problems.push(
    `maplibre-gl ${version}: the worker no longer imports "${SHARED_SPECIFIER}". Copying ${MAPLIBRE_WORKER_ASSETS.join(" + ")} would ship a worker that cannot load — silently, with a green build and an empty map.`,
  );
}

// --- 5. if the copies exist, they are the installed ones ------------------
let compared = 0;
if (existsSync(MAPLIBRE_PUBLIC_DIR)) {
  for (const name of MAPLIBRE_WORKER_ASSETS) {
    const served = join(MAPLIBRE_PUBLIC_DIR, name);
    if (!existsSync(served)) {
      problems.push(`${MAPLIBRE_PUBLIC_DIR}/${name} is missing — run \`tsx ${COPY_SCRIPT}\`.`);
      continue;
    }
    if (sha(served) !== sha(join(dist, name))) {
      problems.push(
        `${MAPLIBRE_PUBLIC_DIR}/${name} is not the installed maplibre-gl ${version}. A stale worker fails the same silent way a missing one does.`,
      );
    }
    compared++;
  }
}

if (problems.length > 0) {
  console.error(`\n✗ maplibre worker wiring FAILED\n\n${problems.join("\n\n")}\n`);
  process.exit(1);
}

const copiesNote = compared === 0 ? " (none on disk yet — generated at build)" : "";
console.log(
  `✓ maplibre worker wiring clean — maplibre-gl ${version}; ${sources.length} source file(s) scanned, every runtime load goes through ${LOADER}; prebuild/predev regenerate ${MAPLIBRE_WORKER_ASSETS.length} asset(s); ${compared} served copy/copies checked against node_modules${copiesNote}.`,
);
